# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMhW_d4P-QtIBh6KfdAAGHYy63j_7WH1
"""

n = int(input("Enter a positive integer"))
print(n)

S = 0 # biến số dùng để lưu tổng
# Nhập code của bạn vào đây

print(f"the sum of 1 to {n} is {S}")