# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tmRIghUUh2GRQoPtbZ6GWO9tZ1m6aDSq
"""

def uscnn(a,b):
    if (b==0):
        return a;
    return uscnn(b,a%b);
a = int(input('a= '))
b = int(input('b= '))
print("Ước số chung nhỏ nhất của", a, "và", b, "là", uscnn(a,b))