# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIp-ceuDCy3XESfOWvwaNVdmGOdIT-D7
"""

while True:
    try:
        n_str = input("Enter a positive integer: ")
        n = int(n_str)
        if n <= 0:
            print("Please enter a positive integer.")
        else:
            break
    except ValueError:
        print("Invalid input. Please enter a whole number.")
print(n)

s = 0 # biến số dùng để lưu tổng
# Nhâp code của bạn vào đây

print(f"The sum of 1 to {n} is {s}")